#### Importing the Libraries

In [1]:
import pandas as pd 
import numpy as np

In [6]:
import os
print(os.getcwd())
print(os.chdir('C:\\Users\\AYODOTUN\\Documents\\UDemy Data Repository'))
os.getcwd()

C:\Users\AYODOTUN
None


'C:\\Users\\AYODOTUN\\Documents\\UDemy Data Repository'

#### Load the data

In [7]:
data_preprocessed = pd.read_csv('Absenteeism_Preprocessed.csv')
data_preprocessed[:5]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

In [4]:
data_preprocessed.shape


(700, 15)

#### Creating Target

Logistic Regression will be used to classify people into those who have been excessively absent and those who have not. Median value of absenteeism hours will be taken to separate workers into these two classes

In [5]:
#Finding the median
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

Anyone absent for more than 3 hours takes a value of 1, otherwise 0. These values form our targets. We use numpy function of this structure 'np.where(condition, value if True, value if Fasle)

In [6]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 3,1,0)

In [7]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [8]:
#The above is better done using the pandas parametrisation for easier understanding of the code
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > data_preprocessed['Absenteeism Time in Hours'].median(),1,0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [9]:
#Mapping the data into two classes
data_preprocessed['Excessive Absenteeism']= targets
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

#### A comment on the targets

Using the median is numerically stable as it balances the dataset. A balance distribution will prevent the model from learning to output one of the classes exclusively. We can prove this by dividing the total number of 1s by total
Note: A 60/40 distribution will also work well for logistic regression but not for certain algorithms like neural networks

In [10]:
#Shows 54% of targes are 0 since about 46% are 1s which means almost 50/50 balance
targets.sum()/targets.shape[0]

0.45571428571428574

In [11]:
#We can now drop the Absenteeism Time in Hours since we won't be needing it
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours','Day of the Week', 'Distance to Work', 'Daily Work Load Average'], axis = 1)

In [12]:
#To check we successfully dropped it, we use the reserved word 'IS':
data_with_targets is data_preprocessed

False

In [13]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0         0         0         0         1            7   
1         0         0         0         0            7   
2         0         0         0         1            7   
3         1         0         0         0            7   
4         0         0         0         1            7   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                     289   33               30          0         2     1   
1                     118   50               31          0         1     0   
2                     179   38               31          0         0     0   
3                     279   39               24          0         2     0   
4                     289   33               30          0         2     1   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

#### Select the inputs for the regression

In [14]:
data_with_targets.shape

(700, 12)

In [15]:
data_with_targets.iloc[:,0:14] #data_with_targets.iloc[:,:14] yields same result. A better way of doing this for regression is data_with_targets.iloc[:,:-1]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                       289   33               30          0         2     1   
1                       118   50               31          0         1     0   
2                       179   38               31          0         0     0   
3                       279   39               24          0         2     0   
4                       289   33               30          0         2     1   
..                      ...  ...              ...        ...       ...   ...   
695                     179   40               22          1         2     0   
696                     225   28               24          0         1     2   
697                     330   28               25          1         0     0   
698                     235   32               25          1         0     0   
699                     291   40               25          0         1     1   

     Excessive Absenteeism  
0                        1  
1                        0  
2                        0  
3                        1  
4                        0  
..                     ...  
695                      1  
696                      0  
697                      1  
698                      0  
699                      0  

[700 rows x 12 columns]

In [16]:
unscaled_inputs = data_with_targets.iloc[:,:-1]
unscaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  
0                       289   33               30          0         2     1  
1                       118   50               31          0         1     0  
2                       179   38               31          0         0     0  
3                       279   39               24          0         2     0  
4                       289   33               30          0         2     1  
..                      ...  ...              ...        ...       ...   ...  
695                     179   40               22          1         2     0  
696                     225   28               24          0         1     2  
697                     330   28               25          1         0     0  
698                     235   32               25          1         0     0  
699                     291   40               25          0         1     1  

[700 rows x 11 columns]

#### Standardize the data

The codes in comments in immediate next cell is a delibrate error of not standardizing before dummies creation which makes data uninterpretable. We should have standardized before creating the dummies. Reference is made to this in a cell ahead

In [17]:
'''Note: The codes in comments were used initially but now commented to apply the approach of the codes in subsequent cells'''
#Standardisation 
#from sklearn.preprocessing import StandardScaler
#absenteeism_scaler = StandardScaler() #declaring an empty standardscaler object. It will subtract the mean from all datapoints and divide by standard deviation

'Note: The codes in comments were used initially but now commented to apply the approach of the codes in subsequent cells'

The codes in next five cells below now correct the delibrate error. It is the custom scaler that allows the choosing of columns to scale. We return to the last checkpoint of unscaled inputs and create a new variable of features(columns) to scale, ommitting the dummies from the features(columns).Then apply the CustomScaler.

In [18]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator, TransformerMixin):
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True): #the 'columns' arguement enables scaling of selected columns alone
        self.scaler = StandardScaler(copy,with_mean,with_std)
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ =np.var(X[self.columns], y)
        return self
    
    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]),columns=self.columns)
        X_not_scaled = X.loc[:, ~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]
    
        

In [19]:
unscaled_inputs.columns.values #To see the columns in the unscaled inputs

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [20]:
#Creating the varible that tells columns to scale, excluding the dummies
'''columns_to_scale = ['Month Value','Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index','Children', 'Pets']'''

columns_to_omit= ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Education']

In [21]:
#This is List Comprehension enabling the creation of a list from a list
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [1]:
#Declare the absenteeism scaler
absenteeism_scaler = CustomScaler(columns_to_scale)

NameError: name 'CustomScaler' is not defined

In [23]:
absenteeism_scaler.fit(unscaled_inputs) #Calculates the mean and S.D from the unscaled data and stores it in the absenteeism_scaler. This only prepares the scaling mechanism

C:\Users\AYODOTUN\Anaconda3\lib\site-packages\sklearn\base.py:197: FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
  FutureWarning)


CustomScaler(columns=['Month Value', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'],
             copy=None, with_mean=None, with_std=None)

In [24]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs) #This now applies the information in the standardscaler on the input

In [25]:
scaled_inputs #Now all except the dummies are scaled

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1     0.030796   
1           0         0         0         0     0.030796   
2           0         0         0         1     0.030796   
3           1         0         0         0     0.030796   
4           0         0         0         1     0.030796   
..        ...       ...       ...       ...          ...   
695         1         0         0         0    -0.568019   
696         1         0         0         0    -0.568019   
697         1         0         0         0    -0.568019   
698         0         0         0         1    -0.568019   
699         0         0         0         1    -0.568019   

     Transportation Expense       Age  Body Mass Index  Education  Children  \
0                  1.005844 -0.536062         0.767431          0  0.880469   
1                 -1.574681  2.130803         1.002633          0 -0.019280   
2                 -0.654143  0.248310         1.002633          0 -0.919030   
3                  0.854936  0.405184        -0.643782          0  0.880469   
4                  1.005844 -0.536062         0.767431          0  0.880469   
..                      ...       ...              ...        ...       ...   
695               -0.654143  0.562059        -1.114186          1  0.880469   
696                0.040034 -1.320435        -0.643782          0 -0.019280   
697                1.624567 -1.320435        -0.408580          1 -0.919030   
698                0.190942 -0.692937        -0.408580          1 -0.919030   
699                1.036026  0.562059        -0.408580          0 -0.019280   

         Pets  
0    0.268487  
1   -0.589690  
2   -0.589690  
3   -0.589690  
4    0.268487  
..        ...  
695 -0.589690  
696  1.126663  
697 -0.589690  
698 -0.589690  
699  0.268487  

[700 rows x 11 columns]

In [26]:
scaled_inputs.shape

(700, 11)

One way to avoid overfitting is to hide a small part of the data from the algorithm and then use it to assess its accuracy on a data it had not see before. We also shuffle the data to remove all forms of dependency in the data such as day of the week. So we split the data into train and test

In [27]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets)

In [28]:
print(x_train.shape, y_train.shape) #Targets has only one dimension since it is the outcome variable

(525, 11) (525,)


In [29]:
print(x_test.shape, y_test.shape)

(175, 11) (175,)


Note above that the ratio of x to y is 0.75 to 0.25. This is the default split. But in most cases, 0.80 to 0.20 split is preferred. We can now pass this parameter in the train_test_split function.

In [30]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.80)
print(x_train.shape, y_train.shape)

(560, 11) (560,)


The train test split has a shuffling parameter which returns a boolean. The shuffle is set to True by default. Hence, each time the train test split function is re-run, it returns different train test split or shuffle causing the final model to differ all  the time with varying accuracy. Therefore, setting a random state parameter makes the shuffling pseudo random i.e shuffle the observations in the same 'random' way

In [31]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.8, random_state = 20)
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(560, 11) (560,)
(140, 11) (140,)


#### Logistic Regression with sklearn

Note: Statsmodels are sorts of imperfect libraries which are not numerically stable for training complicated machine learning models. We therefore turn to sklearn

In [32]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics


#### Training the model

In [33]:
reg = LogisticRegression()


In [34]:
reg.fit(x_train, y_train) #Note that we left most of the parameters as default

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

After rescaling without dummies,accuracy drops by about 1% since we changed about 5 input features. However, we only traded accuracy for interpretability.

In [35]:
#Let's check accuracy. This shows the model predicted 80% of the data accurately
reg.score(x_train, y_train)

0.7767857142857143

#### Manually check the accuracy

The LR model is trained on a training input. Based on them it finds outputs which are trying to be as close as possible to the target. However, accuracy means 80% of the output march the target. To find the accuracy manually, we find the outputs and compare them with the target. We use predict method of the sklearn.

In [36]:
model_output = reg.predict(x_train)
model_output

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [37]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [38]:
model_output == y_train   #To see a boolean showing where the two match

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [39]:
#To get the total number of true matches
np.sum(model_output==y_train)

435

In [40]:
model_output.shape[0] #The total number of entries

560

In [41]:
#Dividing the total number of matches by total number of entries gives the accuracy
np.sum(model_output==y_train)/model_output.shape[0]

0.7767857142857143

#### Finding the intercept and the coefficients

In [42]:
reg.intercept_

array([-1.60957471])

In [43]:
reg.coef_

array([[ 2.77151176,  0.93168817,  3.09210221,  0.8090592 ,  0.00781237,
         0.62505482, -0.17390339,  0.28829409, -0.24081615,  0.35753531,
        -0.27337422]])

In [44]:
#To see the variables associated with the coefficients
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [45]:

feature_name = unscaled_inputs.columns.values

In [46]:
#Declare a new dataframe that contains the intercept, coefficients and the variables
summary_table = pd.DataFrame(columns=['feature_name'], data = feature_name)
summary_table['Coefficient'] = np.transpose(reg.coef_) #This is necessary since ndarrays are rows rather than columns
summary_table

feature_name  Coefficient
0                 Reason_1     2.771512
1                 Reason_2     0.931688
2                 Reason_3     3.092102
3                 Reason_4     0.809059
4              Month Value     0.007812
5   Transportation Expense     0.625055
6                      Age    -0.173903
7          Body Mass Index     0.288294
8                Education    -0.240816
9                 Children     0.357535
10                    Pets    -0.273374

To add the intercept, we can use the append or concatenate method. These would put it at the end of the table but that is not a good position for the intercept. We can resolve this as follows:

In [47]:
#We can add 1 to all indices of the summary table
summary_table.index = summary_table.index + 1  #This shifts all index by 1 leaving the first index empty
summary_table.loc[0] = ['intercept', reg.intercept_[0]]  #Filling up the empty zero index
summary_table = summary_table.sort_index()
summary_table

feature_name  Coefficient
0                intercept    -1.609575
1                 Reason_1     2.771512
2                 Reason_2     0.931688
3                 Reason_3     3.092102
4                 Reason_4     0.809059
5              Month Value     0.007812
6   Transportation Expense     0.625055
7                      Age    -0.173903
8          Body Mass Index     0.288294
9                Education    -0.240816
10                Children     0.357535
11                    Pets    -0.273374

#### Interpreting the coefficients

Coefficients are also called weights and the intercepts called bias. The weight shows how we weigh certain features. The closer the weights are to zero, the smaller they are and the further away from zero, whether positive or negative, the bigger the weight of the feature. This only applies to models of same-scale variables alone. So we need to standardize such that all variables have same variance. When features are standardized, they all are having a variance of 1, then a bigger weight corresponds to more importance. 
<br>
Note: Logistic regression can be said to be a linear model predicting log odds which are later transformed into 0 and 1s. To make them more interpretable, we find the exponentials of the coefficients as follows:

In [48]:
#Odd ratios are gotten from finding the exponentials of the coefficients
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [49]:
summary_table #The new column of exponentials of coefficients(odds ratio) is now added

feature_name  Coefficient  Odds_ratio
0                intercept    -1.609575    0.199973
1                 Reason_1     2.771512   15.982778
2                 Reason_2     0.931688    2.538791
3                 Reason_3     3.092102   22.023327
4                 Reason_4     0.809059    2.245794
5              Month Value     0.007812    1.007843
6   Transportation Expense     0.625055    1.868348
7                      Age    -0.173903    0.840378
8          Body Mass Index     0.288294    1.334150
9                Education    -0.240816    0.785986
10                Children     0.357535    1.429801
11                    Pets    -0.273374    0.760808

In [50]:

summary_table.sort_values('Odds_ratio', ascending  = False) #Sorting from most important to the least important

feature_name  Coefficient  Odds_ratio
3                 Reason_3     3.092102   22.023327
1                 Reason_1     2.771512   15.982778
2                 Reason_2     0.931688    2.538791
4                 Reason_4     0.809059    2.245794
6   Transportation Expense     0.625055    1.868348
10                Children     0.357535    1.429801
8          Body Mass Index     0.288294    1.334150
5              Month Value     0.007812    1.007843
7                      Age    -0.173903    0.840378
9                Education    -0.240816    0.785986
11                    Pets    -0.273374    0.760808
0                intercept    -1.609575    0.199973

**Interpretation**<br>
A feature is not particularly important if its coefficient is around 0 or if its odds ratio is around 1.

1)In terms of coefficient: A weight(coefficient) of 0 implies that no matter the feature value, we will multiply it by 0( in the model) and the whole result will be 0.

2)In terms of odd ratio: For a unit change in the standardized feature, the odds increase by a multiple equal to the odds ratio. If the odd ratio is 1, the odds don't change at all.
<table border "none">
				<tr><td>ODDS RATIO</td><td></td><td>ODDS</td><td>NEW ODDS(for a unit change)</td></tr>
				<tr><td>5:1</td><td>X</td><td>2 </td><td>10:1 </td></tr>
				<tr><td>5:1</td><td>X</td><td>0.2 </td><td>1:1</td></tr>
                <tr><td>5:1</td><td>X</td><td>1 </td><td>5:1 (No change)</td></tr>
			</table>

Looking at the summary table, example of the 1 odd(no change) is with the feature "Daily Work Load Average". This feature is therefore useless for our model. "Distance to work" and "Days of the week" are also like that. We may not drop them yet.
Now, reason zero is the baseline against which other reasons are compared. Reason zero means absence for no reason. Now, let's explore how much access of absence will a person get given when he gives any of reason Reason_1 - 4 compared to reason 0.

#### Standardizing the 

Earlier, when standardizing the the inputs, we also standardized the reason dummies. Thus, a unit change is uninterpretable unlike if they had been left as 1s and 0s. To solve this problem we refer to the scaled data checkpoint and put all the codes in comments. Ideally we should have standardized before creating the dummies. Since that was not done, we then go to manipulate the 'columns' argument in the initialisation function of the CustomsScaler class. Since the columns to be standardized will be specified, then we can avoid the dummies columns.(See cells 17 to 25)

#### Backward Elimination

This allows us to remove features that have posted no condtributions to the model(similar to insignificant variables by p-values > 0.05). Since p-values are not shown in sklearn, the engineers who designed sklearn provide that if the weight(coefficient) of an input is close to zero, it won't make any difference. We can go to the last check point "data_with_targets" and remove those variables. The variables are "Days of the Week", "Distance to Work" and "Daily Work Load Average". We comment the intial 'column_to_scale' code and create a new varible "columns_to_ommit".(See cell 20 above)

#### Testing the Model

Since the algorithm has seen the data many times in the training process, it has learnt to model it quite well. However it may fail miserably when provided with new data. So we need to use the test data which always comes up at the end of machine learning to establish the the accuracy by tweaking the model by changing its parameters to get a better accuracy. When this happens iteratively, it becomes a manual training with the test data. This makes the test dataset useless as that can not be called testing. Once we test, we are not conceptually allowed to touch the model anymore. 

In [51]:
#To find the accuracy
reg.score(x_test, y_test)

0.7357142857142858

Note:(1)The above result shows that based on the data the model hasn't seen before in 74% of the cases, the model will predict if an employee will be excessively absent. The test accuracy is always lower than the train accuracy. It can only be higher by luck or an error. Often it is dramatically lower like 10% or 20%, meaning our logistic regression model overfitted and tend to fail in real life.
(2) Instead of using the usual .predict method for the output, we can use the .predict_proba method in sklearn to predict probability ogf 0s and 1s.



In [53]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba  #This is a 140 by 2 array of probability of predicted values being 0 and 1 respectively.
#Note that summing any two values horizontally gives probability of 1

array([[0.75466347, 0.24533653],
       [0.60917591, 0.39082409],
       [0.48329093, 0.51670907],
       [0.75768232, 0.24231768],
       [0.08357741, 0.91642259],
       [0.3052464 , 0.6947536 ],
       [0.303675  , 0.696325  ],
       [0.11636888, 0.88363112],
       [0.7400284 , 0.2599716 ],
       [0.75596036, 0.24403964],
       [0.50609784, 0.49390216],
       [0.19501503, 0.80498497],
       [0.06248668, 0.93751332],
       [0.7055465 , 0.2944535 ],
       [0.29675526, 0.70324474],
       [0.52028649, 0.47971351],
       [0.50551315, 0.49448685],
       [0.50843643, 0.49156357],
       [0.36713074, 0.63286926],
       [0.06422143, 0.93577857],
       [0.73822433, 0.26177567],
       [0.75768232, 0.24231768],
       [0.47994423, 0.52005577],
       [0.47760936, 0.52239064],
       [0.22619725, 0.77380275],
       [0.74047815, 0.25952185],
       [0.51148533, 0.48851467],
       [0.87702735, 0.12297265],
       [0.24005377, 0.75994623],
       [0.75768232, 0.24231768],
       [0.

In [59]:
#Probability of getting 1(absenteeism) is separated from this array by slicing the second column
predicted_proba[:,1]

array([0.24533653, 0.39082409, 0.51670907, 0.24231768, 0.91642259,
       0.6947536 , 0.696325  , 0.88363112, 0.2599716 , 0.24403964,
       0.49390216, 0.80498497, 0.93751332, 0.2944535 , 0.70324474,
       0.47971351, 0.49448685, 0.49156357, 0.63286926, 0.93577857,
       0.26177567, 0.24231768, 0.52005577, 0.52239064, 0.77380275,
       0.25952185, 0.48851467, 0.12297265, 0.75994623, 0.24231768,
       0.38859882, 0.71238179, 0.69821485, 0.49507156, 0.24231768,
       0.59772596, 0.26042186, 0.78022686, 0.4398591 , 0.60641126,
       0.24188848, 0.49713003, 0.25862385, 0.40689715, 0.80759194,
       0.59889345, 0.71944702, 0.24317762, 0.24676126, 0.2414598 ,
       0.50180816, 0.29299268, 0.6947536 , 0.24459387, 0.82033268,
       0.39193844, 0.90599346, 0.26442957, 0.32150234, 0.3220128 ,
       0.70502976, 0.69623972, 0.26579672, 0.77584327, 0.24541121,
       0.24490372, 0.07551158, 0.26087263, 0.76176924, 0.29640101,
       0.25772789, 0.31539593, 0.88408057, 0.4387068 , 0.59547

In reality, logistic regression model calculates these probabilities in the background. Where probability is below 0.5, it places a 0,otherwise 1.

#### Saving the Model

This is a process of creating a file containing all the information on the machine learning. The object "reg"( an instance of the LogisticRegression class in output line 34) contains all the information to be rendered in the file. We use python module "pickle" to convert the object into a character string. This can be reversed by "unpickle"

In [60]:
import pickle

The file name is MODEL, wb means WRITE BITES. Converstsely when we unpicke, we use "rb" meaning rebyte'. We DUMP the object when we pickle but LOAD when we unpickle. In the .dump method, we specify "reg" object''


In [62]:
 with open('model','wb') as file:
    pickle.dump(reg, file) 

#### Saving the absenteeism sclar

This is essential as was used to save the mean and the standard deviations of each feature. Since we have trained the model and obtained coefficients for them, saving it now means we have separated the model from the training data so as to be able to use it on any new data. Similarly saving the absenteeism scalar is needed to be able to use the information in it on new data. So we pickle it as follows:

In [63]:
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler, file) 